					<br class="clearboth"/>
					<p id="contentInnerBottom"/>
				</div>
				<p id="contentBottom"/>
			</div>
			<br class="clearboth"/>
			<p id="mainContentBottomShadow"/>
		</div>
		<div id="mainFooter">
			<ul>
				<li><a href="http://www.ethique.gouv.qc.ca/Confidentiality-Policy.html">Confidentiality Policy</a> |</li>
				<li><a href="http://www.ethique.gouv.qc.ca/Code-of-Ethics-and-Professional.html">Code of Ethics and Professional conduct</a> |</li>
				<li><a href="http://www.ethique.gouv.qc.ca/Website-design.html">Website design</a></li>
			</ul>
			<img alt="Québec" src="http://www.ethique.gouv.qc.ca/media/img/mainFooter_logo_quebec.gif" width="105" height="32" />
			<p>&copy; Tous droits réservés, 2007 - Gouvernement du Québec</p>
		</div>