<style type="text/css">

	#bandeauRecherche {
		margin-left:  17px;
		margin-right: 17px;
		background-image:none;
	}
	
	#bandeauRecherche h1{
		display:none;
	}
	
	#resultatsRecherche {
		margin-left:  17px;
		margin-right: 17px;
		width: 530px;
	}
</style>

		<div id="mainHeader">
			<a href="http://www.ethique.gouv.qc.ca/" id="mainHeaderLogo"><img alt="Commission de l'éthique de la science et de la technologie (CEST)" src="http://www.ethique.gouv.qc.ca/media/img/mainHeader_logo_cest.gif" class="floatLeft" width="194" height="77" /></a>
			<div id="mainHeaderBandeau">
				<img alt="Bandeau" src="http://www.ethique.gouv.qc.ca/media/img/mainHeader_bandeau.jpg" width="450" height="57" />
				<ul id="mainHeaderMenuEs">
					<li id="mainHeaderMenuEs1"><a href="http://www.ethique.gouv.qc.ca/@@_es.html" title=""><span>Inicio</span></a></li>
					<li id="mainHeaderMenuEs2"><a href="http://www.ethique.gouv.qc.ca/@@@_plano_del_sitio.html" title=""><span>Plano del sitio</span></a></li>
					<li id="mainHeaderMenuEs3"><a href="http://www.ethique.gouv.qc.ca/Correo.html" title=""><span>Correo</span></a></li>
					<li id="mainHeaderMenuEs4"><a href="http://www.gouv.qc.ca" title="Portal Québec"><span>Portal Québec</span></a></li>
					<li id="mainHeaderMenuEs5"><a href="./" title=""><span>Buscar</span></a></li>
					<li id="mainHeaderMenuEs6"><a href="http://www.ethique.gouv.qc.ca/@@_fr.html" title="Français"><span>Français</span></a></li>
					<li id="mainHeaderMenuEs7"><a href="http://www.ethique.gouv.qc.ca/@@_en.html" title="English"><span>English</span></a></li>
				</ul>
			</div>
		</div>
		<div id="mainContent">
			<p id="mainContentTopShadow"/>
			<div id="mainContentWrapper">
				<div id="leftMenu">
					<ul>
						<li class="menuElement">
							<a href="javascript:void(0);" title="La Comisión">La Comisión</a>
							<ul style="display: none;">
								<li class="sousMenuFirstElement"><a href="http://www.ethique.gouv.qc.ca/La-Comision.html" title="La Comisión" accesskey="a">La Comisión</a></li>
								<li><a href="http://www.ethique.gouv.qc.ca/Descripcion-de-la-CEST.html" title="Descripción de la CEST" accesskey="b">Descripción de la CEST</a></li>
								<li><a href="http://www.ethique.gouv.qc.ca/Mision-y-mandato.html" title="Misión y mandato" accesskey="c">Misión y mandato</a></li>
								<li><a href="http://www.ethique.gouv.qc.ca/Dominio-de-reflexion.html" title="Dominio de reflexión" accesskey="d">Dominio de reflexión</a></li>
								<li><a href="http://www.ethique.gouv.qc.ca/Los-miembros-de-la-CEST.html" title="Los miembros de la CEST" accesskey="e">Los miembros de la CEST</a></li>
								<li class="sousMenuLastElement"><a href="http://www.ethique.gouv.qc.ca/La-secretaria-de-la-CEST.html" title="La secretaría de la CEST" accesskey="f">La secretaría de la CEST</a></li>
							</ul>
						</li>
						<li class="menuElement">
							<a href="http://www.ethique.gouv.qc.ca/-Publicaciones-.html" title="Publicaciones">Publicaciones</a>
						</li>
						<li class="menuElement">
							<a href="javascript:void(0);" title="Proyectos">Proyectos</a>
							<ul style="display: none;">
								<li class="sousMenuElementSeul"><a href="http://www.ethique.gouv.qc.ca/-Proyectos-corrientes-.html" title="Proyectos corrientes" accesskey="g">Proyectos corrientes</a></li>
							</ul>	
						</li>
						<li class="menuElement">
							<a href="http://www.ethique.gouv.qc.ca/-Otros-sitios-.html" title="Otros sitios">Otros sitios</a>
						</li>
						<li class="menuElement">
							<a href="http://www.ethique.gouv.qc.ca/-Que-hay-de-nuevo-.html" title="¿Qué hay de nuevo?">¿Qué hay de nuevo?</a>
						</li>
						<li class="iconsElement">
							<a href="javascript:void(0);" onclick="Actions.fontSizeDown(); return false;"><img alt="Disminuir el tamaño de fuente" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_iconedown.gif" width="16" height="16" /></a>
							<a href="javascript:void(0);" onclick="Actions.fontSizeUp(); return false;"><img alt="Aumentar el tamaño de fuente" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_iconeup.gif" width="16" height="16" /></a>
							<a href="javascript:void(0);" onclick="Actions.printPage(); return false;"><img alt="Imprimir la página" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_iconeprint.gif" width="16" height="16" /></a>
							<a href="javascript:void(0);" onclick="Actions.openForwardBox(); return false;"><img alt="Enviar esta página por el email" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_iconemail.gif" width="16" height="16" /></a>
						</li>
					</ul>
					<p id="themaLinksTopShadow"/>
					<div id="themaLinks">
						<div id="forwardToBox" style="display: none;">
							<form action="@-recherche.html" id="forwardToForm" name="forwardToForm" onsubmit="Actions.forwardPage.init(); return false;">
								<h2>Enviar esta página</h2>
								<label for="forwardToBoxFrom">De:</label>
								<input type="text" name="forwardToBoxFrom" id="forwardToBoxFrom" title="" maxlength="40" />
								<label for="forwardToBoxTo">A:</label>
								<input type="text" name="forwardToBoxTo" id="forwardToBoxTo" title="" maxlength="40" />
								<input type="hidden" name="forwardToBoxLang" value="es" />
								<input type="hidden" name="forwardToBoxTitle" value="Commission de l'éthique de la science et de la technologie (CEST)" />
								<input type="hidden" name="forwardToBoxUrl" value="http://www.ethique.gouv.qc.ca/@@_es.html" />
								<input type="submit" id="forwardToBoxSubmit" />
							</form>
							<hr/>
						</div>
						<a href="http://www.ethique.gouv.qc.ca/BIG/"><img alt="BIG - Les Banques d'information Génétique" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_logo_big.gif" width="149" height="41" /></a>
						<hr/>
						<a href="http://www.ethique.gouv.qc.ca/OGM/"><img alt="Pour une gestion éthique des Organismes Génétiquement Modifiés (OGM)" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_logo_ogm.gif" width="149" height="53" /></a>
					<p id="themaLinksBottom"/>
					</div>
					<p id="cstLinkTop"/>
					<div id="cstLink">
						<a href="http://www.cst.gouv.qc.ca"><img alt="CST" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_logo_cst.gif" width="140" height="43" /></a>
					</div>
					<p id="cstLinkBottom"/>
					<p id="leftMenuBottom"/>
				</div>
				<div id="content">
					<h1>Buscar</h1>