<style type="text/css">

	#bandeauRecherche {
		margin-left:  17px;
		margin-right: 17px;
		background-image:none;
	}
	
	#bandeauRecherche h1{
		display:none;
	}
	
	#resultatsRecherche {
		margin-left:  17px;
		margin-right: 17px;
		width: 530px;
	}
</style>

		<div id="mainHeader">
			<a href="http://www.ethique.gouv.qc.ca/" id="mainHeaderLogo"><img alt="Commission de l'éthique de la science et de la technologie (CEST)" src="http://www.ethique.gouv.qc.ca/media/img/mainHeader_logo_cest.gif" class="floatLeft" width="194" height="77" /></a>
			<div id="mainHeaderBandeau">
				<img alt="Bandeau" src="http://www.ethique.gouv.qc.ca/media/img/mainHeader_bandeau.jpg" width="450" height="57" />
				<ul id="mainHeaderMenuEn">
					<li id="mainHeaderMenuEn1"><a href="http://www.ethique.gouv.qc.ca/@@_en.html" title="Home"><span>Home</span></a></li>
					<li id="mainHeaderMenuEn2"><a href="http://www.ethique.gouv.qc.ca/@@@_site_map.html" title="Site map"><span>Site map</span></a></li>
					<li id="mainHeaderMenuEn3"><a href="http://www.ethique.gouv.qc.ca/Contact.html" title="Email"><span>Email</span></a></li>
					<li id="mainHeaderMenuEn4"><a href="http://www.gouv.qc.ca" title="Portail Québec"><span>Portail Québec</span></a></li>
					<li id="mainHeaderMenuEn5"><a href="./" title=""><span>Research</span></a></li>
					<li id="mainHeaderMenuEn6"><a href="http://www.ethique.gouv.qc.ca/@@_fr.html" title=""><span>Français</span></a></li>
					<li id="mainHeaderMenuEn7"><a href="http://www.ethique.gouv.qc.ca/@@_es.html" title=""><span>Espa&ntilde;ol</span></a></li>
				</ul>
			</div>
		</div>
		<div id="mainContent">
			<p id="mainContentTopShadow"/>
			<div id="mainContentWrapper">
				<div id="leftMenu">
					<ul>
						<li class="menuElement">
							<a href="javascript:void(0);" title="The Commission">The Commission</a>
							<ul style="display: none;">
								<li class="sousMenuFirstElement"><a href="http://www.ethique.gouv.qc.ca/The-Commission.html" title="The Commission" accesskey="a">The Commission</a></li>
								<li><a href="http://www.ethique.gouv.qc.ca/Description-of-the-CEST.html" title="Description of the CEST" accesskey="b">Description of the CEST</a></li>
								<li><a href="http://www.ethique.gouv.qc.ca/Mission-and-mandate.html" title="Mission and mandate" accesskey="c">Mission and mandate</a></li>
								<li><a href="http://www.ethique.gouv.qc.ca/Scope-of-Deliberations.html" title="Scope of Deliberations" accesskey="d">Scope of Deliberations</a></li>
								<li><a href="http://www.ethique.gouv.qc.ca/Members-of-the-CEST.html" title="Members of the CEST" accesskey="e">Members of the CEST</a></li>
								<li class="sousMenuLastElement"><a href="http://www.ethique.gouv.qc.ca/The-CEST-secretariat.html" title="The CEST secretariat" accesskey="f">The CEST secretariat</a></li>
							</ul>
						</li>
						<li class="menuElement">
							<a href="http://www.ethique.gouv.qc.ca/-Publications,13-.html" title="Publications">Publications</a>
						</li>
						<li class="menuElement">
							<a href="javascript:void(0);"" title="Projects">Projects</a>
							<ul style="display: none;">
								<li class="sousMenuElementSeul"><a href="http://www.ethique.gouv.qc.ca/-Current-projects-.html" title="Current projects" accesskey="g">Current projects</a></li>
							</ul>
						</li>
						<li class="menuElement">
							<a href="http://www.ethique.gouv.qc.ca/-Links-.html" title="Links">Links</a>
						</li>
						<li class="menuElement">
							<a href="http://www.ethique.gouv.qc.ca/-What-s-new-.html" title="What&#8217;s new ?">What&#8217;s new ?</a>
						</li>
						<li class="iconsElement">
							<a href="javascript:void(0);" onclick="Actions.fontSizeDown(); return false;"><img alt="Decrease font size" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_iconedown.gif" width="16" height="16" /></a>
							<a href="javascript:void(0);" onclick="Actions.fontSizeUp(); return false;"><img alt="Increase font size" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_iconeup.gif" width="16" height="16" /></a>
							<a href="javascript:void(0);" onclick="Actions.printPage(); return false;"><img alt="Print the page" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_iconeprint.gif" width="16" height="16" /></a>
							<a href="javascript:void(0);" onclick="Actions.openForwardBox(); return false;"><img alt="Send this page by email" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_iconemail.gif" width="16" height="16" /></a>
						</li>
					</ul>
					<p id="themaLinksTopShadow"/>
					<div id="themaLinks">
						<div id="forwardToBox" style="display: none;">
							<form action="@-recherche.html" id="forwardToForm" name="forwardToForm" onsubmit="Actions.forwardPage.init(); return false;">
								<h2>Send this page</h2>
								<label for="forwardToBoxFrom">To:</label>
								<input type="text" name="forwardToBoxFrom" id="forwardToBoxFrom" title="" maxlength="40" />
								<label for="forwardToBoxTo">From:</label>
								<input type="text" name="forwardToBoxTo" id="forwardToBoxTo" title="" maxlength="40" />
								<input type="hidden" name="forwardToBoxLang" value="en" />
								<input type="hidden" name="forwardToBoxTitle" value="Commission de l'éthique de la science et de la technologie (CEST)" />
								<input type="hidden" name="forwardToBoxUrl" value="@@_en.html" />
								<input type="submit" id="forwardToBoxSubmit" />
							</form>
							<hr/>
						</div>
						<a href="http://www.ethique.gouv.qc.ca/BIG/"><img alt="BIG - Les Banques d'information Génétique" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_logo_big.gif" width="149" height="41" /></a>
						<hr/>
						<a href="http://www.ethique.gouv.qc.ca/OGM/"><img alt="Pour une gestion éthique des Organismes Génétiquement Modifiés (OGM)" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_logo_ogm.gif" width="149" height="53" /></a>
					<p id="themaLinksBottom"/>
					</div>
					<p id="cstLinkTop"/>
					<div id="cstLink">
						<a href="http://www.cst.gouv.qc.ca"><img alt="CST" src="http://www.ethique.gouv.qc.ca/media/img/leftMenu_logo_cst.gif" width="140" height="43" /></a>
					</div>
					<p id="cstLinkBottom"/>
					<p id="leftMenuBottom"/>
				</div>
				<div id="content">
					<h1>Search</h1>
