		<title>Search - Commission de l'éthique de la science et de la technologie (CEST)</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="imagetoolbar" content="no" />
		<link rel="alternate" href="http://www.ethique.gouv.qc.ca/@@_fr.html" hreflang="fr" title="Français [fr]" />
		<link rel="alternate" href="http://www.ethique.gouv.qc.ca/@@_es.html" hreflang="es" title="espa&ntilde;ol [es]" />
		<link rel="alternate" type="application/rss+xml" title="Syndicate the whole site" href="http://www.ethique.gouv.qc.ca/@@@_backend_en.rss" />
		<link rel="stylesheet" type="text/css" href="http://www.ethique.gouv.qc.ca/media/css/main.style.css" media="screen, print" />
		<link rel="stylesheet" type="text/css" href="http://www.ethique.gouv.qc.ca/media/css/print.style.css" media="print" />
		<link rel="alternate stylesheet" type="text/css" href="http://www.ethique.gouv.qc.ca/media/css/bigfont.style.css" title="bigfont" />
		<link rel="alternate stylesheet" type="text/css" href="http://www.ethique.gouv.qc.ca/media/css/smallfont.style.css" title="smallfont" />
		<script type="text/javascript" src="http://www.ethique.gouv.qc.ca/media/js/prototype.js"></script>
		<script type="text/javascript" src="http://www.ethique.gouv.qc.ca/media/js/scriptaculous/scriptaculous.js"></script>
		<script type="text/javascript" src="http://www.ethique.gouv.qc.ca/media/js/javascript.extensions.js"></script>
		<script type="text/javascript" src="http://www.ethique.gouv.qc.ca/media/js/cest.menu.js"></script>
		<script type="text/javascript" src="http://www.ethique.gouv.qc.ca/media/js/styleswitcher.js"></script>
