<center>
<table id="bas_page" width="429" cellpadding="0" cellspacing="0" border="0" align="center" >
	<tr>
		<td valign="top">
		<p align="center">
			<a href="http://mri.gouv.qc.ca/fr/general/politique.asp">Politique de confidentialit&eacute;</a><br>
			<a href="http://mri.gouv.qc.ca/index.asp">Minist&egrave;re des Relations internationales<a><br><br>
			<a href="http://www.gouv.qc.ca/portail/quebec/pgs/commun?lang=fr" target="_blank"><img src="http://www.mri.gouv.qc.ca/_visuel/logo_baspage.gif"  border="0"></a><br><br>

			<a href="http://www.droitauteur.gouv.qc.ca/copyright.php" target="_blank">
			&copy; Gouvernement du Qu&eacute;bec, 2007</a><br /><br />
		</td>
	</tr>	
</table>
</center>