<center>
<table width="760" height="96" cellpadding="0" cellspacing="0" border="0">
	<tr>
		<td valign="top" width="209" height="96"><a href="http://www.mri.gouv.qc.ca/index.asp"><img src="http://www.mri.gouv.qc.ca/_visuel/logo.gif" border="0" title="http://www.mri.gouv.qc.ca"></a></td>
		<td valign="top" width="551" height="96">
			<table width="551" height="96" cellpadding="0" cellspacing="0">
				<tr>
					<td valign="top" width="551" height="57"><img src="http://www.mri.gouv.qc.ca/_visuel/bandeau.gif" border="0"></td>
				</tr>
				<tr>

					<td align="left"  valign="top">
						<table  align="left" width="551" height="15" cellpadding="0" cellspacing="0" bgcolor="#003399">
							<tr>
								<td align="left" width="35"><img src="http://www.mri.gouv.qc.ca/fr/_visuel/piv_bleu.gif" width="35" height="15" border="0"></td>
								<td align="left" width="10%"><a href="http://www.mri.gouv.qc.ca/index.asp"><img src="http://www.mri.gouv.qc.ca/fr/_visuel/piv1.gif" height="15" border="0" title="Accueil"></a></td>
								<td align="left" width="15%"><a href="http://www.mri.gouv.qc.ca/fr/general/coordonnees_ministere.asp"><img src="http://www.mri.gouv.qc.ca/fr/_visuel/piv2.gif" height="15" border="0" title="Courrier"></a></td>
								<td align="left" width="15%"><a href="http://www.gouv.qc.ca" target="_blank"><img src="http://www.mri.gouv.qc.ca/fr/_visuel/piv3.gif" height="15" border="0" title="Portail Québec"></a></td>
								<td align="left" width="15%"><a href="http://www.mri.gouv.qc.ca/fr/general/plan_site.asp"><img src="http://www.mri.gouv.qc.ca/fr/_visuel/piv4.gif" height="15" border="0" title="Plan du site"></a></td>
								<td align="left" width="25%"><img src="http://www.mri.gouv.qc.ca/_visuel/vide.gif"  height="15" border="0" width="100%"></td>

								<td align="right" width="15%"><a href="http://www.mri.gouv.qc.ca/es/"><img src="http://www.mri.gouv.qc.ca/fr/_visuel/piv5.gif" height="15" border="0" title="Español"></a></td>
								<td align="right" width="15%"><a href="http://www.mri.gouv.qc.ca/en/"><img src="http://www.mri.gouv.qc.ca/fr/_visuel/piv6.gif" height="15" border="0" title="English"></a></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td valign="top" width="551" height="24"><img src="http://www.mri.gouv.qc.ca/_visuel/vide.gif" border="0" height="24" width="1"></td>
				</tr>

			</table>
		</td>
	</tr>
</table>
  </center>
