<table width="760px" id="piedpage_recherche">
 <tr>
<td colspan="2" valign="top" id="menubas">
    <div id="haut_space"><a href="#ancre"><img src="http://www.services.gouv.qc.ca/nav/haut.gif" alt="Retour en haut de la page." title="Lien permettant de retourner au début du contenu de la page." width="10" height="16" class="noprint" /></a></div>
	<div id="footerline">&nbsp;</div>
<ul class="menubas">
	  	<li class="menubas">|  <a href="http://www.services.gouv.qc.ca/fr/enligne/index.asp" title="Le gouvernement et les services en ligne." tabindex="900">Gouvernement en ligne</a> |</li>
<li class="menubas"><a href="http://www.services.gouv.qc.ca/fr/administration/index.asp" title="Administration électronique." tabindex="902">Administration électronique</a> |</li>
<li class="menubas"><a href="http://www.services.gouv.qc.ca/fr/securite/index.asp" title="Sécurité de l'information." tabindex="904">Sécurité de l'information</a> |</li>
<li class="menubas"><a href="http://www.services.gouv.qc.ca/fr/connaissances/index.asp" title="Connaissances." tabindex="906">Connaissances</a> |</li>
	<li class="menubas"><a href="http://www.services.gouv.qc.ca/fr/ministere/index.asp" title="Ministère." tabindex="908">Ministère</a> |</li>
</ul>
<br />
<ul class="menubas2">
		<li class="menubas">| <a href="http://www.services.gouv.qc.ca/fr/aerien/index.asp" title="Information sur le service aérien gouvernemental." tabindex="910">Service a&eacute;rien gouvernemental</a> |</li>
		<li class="menubas"><a href="http://www.services.gouv.qc.ca/fr/documentation/index.asp" title="Documentation." tabindex="910">Documentation</a> |</li>
		<li class="menubas"><a href="http://www.services.gouv.qc.ca/fr/accueil/aide.asp" title="Aide à la navigation." tabindex="912">Aide à la navigation</a> |</li>
<li class="menubas"><a href="http://www.services.gouv.qc.ca/fr/accueil/confidentialite.asp" title="Consultez la politique de confidentialité." tabindex="914">Politique de confidentialité</a> |</li>
  <li class="menubas"><a href="http://www.services.gouv.qc.ca/fr/accueil/courrier.asp" title="Pour joindre le ministère." tabindex="916">Pour nous joindre</a> |</li>
</ul>
<div id="date">Derni&egrave;re modification de cette page : 2006-04-12</div>
<a href="http://www.gouv.qc.ca" title="Lien vers le portail national."><img src="http://www.services.gouv.qc.ca/nav/quebw1.gif" alt="Signature du gouvernement du Québec." width="105" height="32" id="logoqc" /></a>  	  	   
<div id="footer" >&copy; <a href="http://www.droitauteur.gouv.qc.ca/copyright.php" title="Dispositions de protection des droits de propriété intellectuelle au gouvernement du Québec">Gouvernement du Qu&eacute;bec, 2005</a></div>
	</td>
  </tr>
</table>