<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr">
<title>Ministère des Services gouvernementaux - Recherche</title>
<meta http-equiv="content-language" content="fr" />
<link rel="schema.DC" href="http://purl.org/dc/elements/1.1/" />
<meta name="dc.language" scheme="ISO639-2" content="fr" />
<meta name="dc.type" content="text" />
<meta name="dc.publisher" content="Ministère des Services gouvernementaux, Direction des affaires publiques et des communications" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<style type="text/css" media="screen">@import url(http://www.services.gouv.qc.ca/styles/recherche.css);</style>
