<table align="center" border="0" cellpadding="0" cellspacing="0" width="740">
  <tbody><tr>
    <td colspan="3" align="middle"><a name="#haut"></a> <img src="http://www.quebecgeographique.gouv.qc.ca/images/bandeau_entete.jpg" usemap="#Map" border="0"> 
  <map name="Map"><area shape="rect" coords="3,38,174,93" href="http://www.gouv.qc.ca/" target="_blank"><area shape="rect" coords="415,55,498,72" href="http://www.gouv.qc.ca/portail/quebec/?lang=fr" target="_blank"><area shape="rect" coords="228,57,269,73" href="http://www.quebecgeographique.gouv.qc.ca/index.asp"><area shape="rect" coords="509,56,568,73" href="http://www.quebecgeographique.gouv.qc.ca/realisation.asp"><area shape="rect" coords="357,56,406,73" href="mailto:service.citoyens@mrnfp.gouv.qc.ca?subject=Information%20-%20Le%20Qu%E9bec%20g%E9ographique"><area shape="rect" coords="283,57,351,74" href="http://www.quebecgeographique.gouv.qc.ca/plan.asp">
    
    
    
    
    
    
  </map>


    </td>
  </tr>
  <tr>
    <td colspan="3" valign="top" width="480"><script language="javascript" type="text/javascript">
function keyWordSearch()
{
	//window.document.recherche.qt.value = window.document.recherche.query.value; masqué par Jean-Pierre Fillion, janvier 2005
	window.document.recherche.method = "get";
	window.document.recherche.action = "search.do";
	if (window.document.recherche.query.value == "")
	{
		window.document.recherche.action="search.do";
	}
	window.document.recherche.submit();
}
</script>

<form name="recherche" onsubmit="javascript:keyWordSearch()">
<!-- <input type="hidden" name="qt"> retiré par Jean-Pierre Fillion, janvier 2005 -->
<input name="Lang" value="fr" type="hidden">
<input name="slang" value="French" type="hidden">
<input name="hx" value="100" type="hidden">
<input name="lx" value="760" type="hidden">
<input name="Fy" value="100" type="hidden">
<input name="mx" value="0" type="hidden">
<input name="mo" value="n" type="hidden">
<input name="rd" value="y" type="hidden">
<input name="cs" value="Iso" type="hidden">
<input name="curl" value="/includes/quebecgeographique/" type="hidden">
<input name="Int" value="qcgeo" type="hidden">
<input name="scatlist" value="qcgeo" type="hidden">
<table align="center" border="0" cellpadding="0" cellspacing="0">
	<tbody><tr>
		<td rowspan="3" height="96" valign="top"><img src="http://www.quebecgeographique.gouv.qc.ca/images/141807.jpg"></td>
		<td colspan="3" valign="top"><img src="http://www.quebecgeographique.gouv.qc.ca/images/entete.jpg" height="56" width="577"></td>
	</tr>
	<tr>
		<td valign="top"><img src="http://www.quebecgeographique.gouv.qc.ca/images/titre_accueil.jpg" height="24" width="305"></td>
		<td align="right" background="http://www.quebecgeographique.gouv.qc.ca/images/entete_recherche.jpg" valign="top" width="236">
		<input name="query" size="7" value="" maxlength="1991" class="Recherche" type="text"></td>
		<td valign="top"><a href="javascript:keyWordSearch()"><img src="http://www.quebecgeographique.gouv.qc.ca/images/entete_ok.jpg" border="0" height="24" width="36"></a></td>
	</tr>
	<tr>
		<td colspan="3" bgcolor="ffffff" valign="top"><img src="http://www.quebecgeographique.gouv.qc.ca/images/carre.GIF" height="16"></td>
	</tr>
</tbody></table>

<!-- 
NOTE. On a noté dans la page maîtresse un espace entre l'entete-portail et le reste de la page (une grosse ligne blanche apparaissait entre l'image "Le Québec géographique" et l'image "Découvrir"). Le seul moyen valable de supprimer cet espace a été de supprimer sans la présente page l'étiquette de fermeture du formulaire, <form>...
Jean-Pierre Fillion, Août 2005
-->
</form></td>
  </tr>
  
  
  <tr>
    <td colspan="3">